// ...existing types...

export interface CartState {
  // ...existing properties...
  updateExtraQuantity: (itemId: string, extraId: string, newQuantity: number) => Promise<void>;
  // ...rest of the properties...
}
